import { ApolloServer } from "@apollo/server";
import { startStandaloneServer } from "@apollo/server/standalone";
import createClient from "openapi-fetch";
import type { paths } from "../generated/guidewire-types"; // generated by bts-sync

const client = createClient<paths>({ baseUrl: "http://localhost:3000" });

const {
  data, // only present if 2XX response
  error, // only present if 4XX or 5XX response
} = await client.GET('/users/{id}', {
  params: {
    path: { id: "123" },
  },
});

// const resolvers = {
//   Query: {
//     getUser: () => {}
//   },
// };

// const server = new ApolloServer({
//   typeDefs,
//   resolvers,
// });

// const { url } = await startStandaloneServer(server, {
//   listen: { port: 4000 },
// });

// console.log(`🚀  Server ready at: ${url}`);